
export  const  GET_E_DATA_LOADING='GET/E_DATA/LOADING'
export  const  GET_E_DATA_SUCCESS='GET/E_DATA/SUCCESS'
export  const  GET_E_DATA_ERROR=  'GET/E_DATA/ERROR'

export  const  GET_ALL_LANGUAGE_LOADING='GET/ALL_LANGUAGE/LOADING'
export  const  GET_ALL_LANGUAGE_SUCCESS='GET/ALL_LANGUAGE/SUCCESS'
export  const  GET_ALL_LANGUAGE_ERROR=  'GET/ALL_LANGUAGE/ERROR'

export  const  GET_SELECTED_LANGUAGE_LOADING='GET/SELECTED_LANGUAGE/LOADING'
export  const  GET_SELECTED_LANGUAGE_SUCCESS='GET/SELECTED_LANGUAGE/SUCCESS'
export  const  GET_SELECTED_LANGUAGE_ERROR=  'GET/SELECTED_LANGUAGE/ERROR'

export  const  UPDATE_SELECTED_LANGUAGE_LOADING='UPDATE/SELECTED_LANGUAGE/LOADING'
export  const  UPDATE_SELECTED_LANGUAGE_SUCCESS='UPDATE/SELECTED_LANGUAGE/SUCCESS'
export  const  UPDATE_SELECTED_LANGUAGE_ERROR=  'UPDATE/SELECTED_LANGUAGE/ERROR'