export  const  ADD_PRODUCT_LOADING='ADD/PRODUCT/LOADING'
export  const  ADD_PRODUCT_SUCCESS='ADD/PRODUCT/SUCCESS'
export  const  ADD_PRODUCT_ERROR='ADD/PRODUCT/ERROR'

export  const  GET_PRODUCT_LOADING='GET/PRODUCT/LOADING'
export  const  GET_PRODUCT_SUCCESS='GET/PRODUCT/SUCCESS'
export  const  GET_PRODUCT_ERROR=  'GET/PRODUCT/ERROR'

export  const  DEBOUNCING_GET_PRODUCT_LOADING='DEBOUNCING/GET/PRODUCT/LOADING'
export  const  DEBOUNCING_GET_PRODUCT_SUCCESS='DEBOUNCING/GET/PRODUCT/SUCCESS'
export  const  DEBOUNCING_GET_PRODUCT_ERROR=  'DEBOUNCING/GET/PRODUCT/ERROR'

export  const  GET_ALL_PRODUCT_LENGTH_LOADING='GET/ALL/PRODUCT/LOADING'
export  const  GET_ALL_PRODUCT_LENGTH_SUCCESS='GET/ALL/PRODUCT/SUCCESS'
export  const  GET_ALL_PRODUCT_LENGTH__ERROR= 'GET/ALL/PRODUCT/ERROR'

export  const  UPDATE_PRODUCT_LOADING='UPDATE/PRODUCT/LOADING'
export  const  UPDATE_PRODUCT_SUCCESS='UPDATE/PRODUCT/SUCCESS'
export  const  UPDATE_PRODUCT_ERROR=  'UPDATE/PRODUCT/ERROR'

export  const  DELETE_PRODUCT_LOADING='DELETE/PRODUCT/LOADING'
export  const  DELETE_PRODUCT_SUCCESS='DELETE/PRODUCT/SUCCESS'
export  const  DELETE_PRODUCT_ERROR=  'DELETE/PRODUCT/ERROR'

export  const  GET_SINGLE_PRODUCT_LOADING='GET_SINGLE/PRODUCT/LOADING'
export  const  GET_SINGLE_PRODUCT_SUCCESS='GET_SINGLE/PRODUCT/SUCCESS'
export  const  GET_SINGLE_PRODUCT_ERROR=  'GET_SINGLE/PRODUCT/ERROR'